.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. wificoin_qt test_wificoin_qt
clean: FORCE
	$(MAKE) -C .. wificoin_qt_clean test_wificoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_wificoin_qt_check
wificoin-qt wificoin-qt.exe: FORCE
	 $(MAKE) -C .. wificoin_qt
